backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "self_transfer_en"
    label: "Self-Transfer (English)"
    label_singular: "Page Content"
    files:
      - file: "src/content/cardContent.en.json"
        label: "English Content"
        name: "self_transfer_en_file"
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            fields:
              - { label: "Headline", name: "headline", widget: string }
              - { label: "Subheadline", name: "subheadline", widget: string }
              - { label: "CTA Label", name: "ctaLabel", widget: string }
              - { label: "CTA Link", name: "ctaLink", widget: string }

          - label: "Intro"
            name: "intro"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: string }
              - { label: "Lead", name: "lead", widget: string }
              - label: "Body"
                name: "body"
                widget: list
                field:
                  label: "Paragraph"
                  name: "paragraph"
                  widget: text

          - { label: "Notice", name: "notice", widget: string }

          - label: "Sections"
            name: "sections"
            widget: object
            fields:
              - { label: "Before", name: "before", widget: string }
              - { label: "During", name: "during", widget: string }

          - label: "Labels"
            name: "labels"
            widget: object
            fields:
              - { label: "Required", name: "Required", widget: string }
              - { label: "Important", name: "Important", widget: string }
              - { label: "Tip", name: "Tip", widget: string }
              - { label: "Done", name: "Done", widget: string }
              - { label: "Mark as Done", name: "Mark as done", widget: string }
              - { label: "Why It Matters", name: "Why It Matters", widget: string }
              - { label: "done (camelCase)", name: "done", widget: string }
              - { label: "markAsDone (camelCase)", name: "markAsDone", widget: string }

          - label: "Cards"
            name: "cards"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: string }
              - { label: "Section", name: "section", widget: string }
              - { label: "Title", name: "title", widget: string }
              - { label: "Front", name: "front", widget: text }
              - { label: "Back", name: "back", widget: text }
              - label: "Label"
                name: "label"
                widget: object
                fields:
                  - { label: "Key", name: "key", widget: string }
                  - { label: "Text", name: "text", widget: string }

          - label: "FAQ"
            name: "faq"
            widget: list
            fields:
              - { label: "Question", name: "question", widget: string }
              - { label: "Answer", name: "answer", widget: text }

          - label: "Guarantee"
            name: "guarantee"
            widget: object
            fields:
              - { label: "Heading", name: "heading", widget: string }
              - { label: "Lead", name: "lead", widget: string }
              - label: "Items"
                name: "items"
                widget: list
                fields:
                  - { label: "Icon", name: "icon", widget: string }
                  - { label: "Title", name: "title", widget: string }
                  - { label: "Description", name: "description", widget: text }
              - { label: "Note", name: "note", widget: text }
              - { label: "Link Text", name: "linkText", widget: string }
              - { label: "Link URL", name: "linkUrl", widget: string }

  - name: "self_transfer_sv"
    label: "Self-Transfer (Swedish)"
    label_singular: "Page Content"
    files:
      - file: "src/content/cardContent.sv.json"
        label: "Swedish Content"
        name: "self_transfer_sv_file"
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            fields:
              - { label: "Headline", name: "headline", widget: string }
              - { label: "Subheadline", name: "subheadline", widget: string }
              - { label: "CTA Label", name: "ctaLabel", widget: string }
              - { label: "CTA Link", name: "ctaLink", widget: string }

          - label: "Intro"
            name: "intro"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: string }
              - { label: "Lead", name: "lead", widget: string }
              - label: "Body"
                name: "body"
                widget: list
                field:
                  label: "Paragraph"
                  name: "paragraph"
                  widget: text

          - { label: "Notice", name: "notice", widget: string }

          - label: "Sections"
            name: "sections"
            widget: object
            fields:
              - { label: "Before", name: "before", widget: string }
              - { label: "During", name: "during", widget: string }

          - label: "Labels"
            name: "labels"
            widget: object
            fields:
              - { label: "Required", name: "Required", widget: string }
              - { label: "Important", name: "Important", widget: string }
              - { label: "Tip", name: "Tip", widget: string }
              - { label: "Done", name: "Done", widget: string }
              - { label: "Mark as Done", name: "Mark as done", widget: string }
              - { label: "Why It Matters", name: "Why It Matters", widget: string }
              - { label: "done (camelCase)", name: "done", widget: string }
              - { label: "markAsDone (camelCase)", name: "markAsDone", widget: string }

          - label: "Cards"
            name: "cards"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: string }
              - { label: "Section", name: "section", widget: string }
              - { label: "Title", name: "title", widget: string }
              - { label: "Front", name: "front", widget: text }
              - { label: "Back", name: "back", widget: text }
              - label: "Label"
                name: "label"
                widget: object
                fields:
                  - { label: "Key", name: "key", widget: string }
                  - { label: "Text", name: "text", widget: string }

          - label: "FAQ"
            name: "faq"
            widget: list
            fields:
              - { label: "Question", name: "question", widget: string }
              - { label: "Answer", name: "answer", widget: text }

          - label: "Guarantee"
            name: "guarantee"
            widget: object
            fields:
              - { label: "Heading", name: "heading", widget: string }
              - { label: "Lead", name: "lead", widget: string }
              - label: "Items"
                name: "items"
                widget: list
                fields:
                  - { label: "Icon", name: "icon", widget: string }
                  - { label: "Title", name: "title", widget: string }
                  - { label: "Description", name: "description", widget: text }
              - { label: "Note", name: "note", widget: text }
              - { label: "Link Text", name: "linkText", widget: string }
              - { label: "Link URL", name: "linkUrl", widget: string }